# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  name: workshop-renovate
  description: ':factory: Workshop renovate'
  homepage: https://ivankatliarchuk.github.io
  topics: ivka, workshop, renovate
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  has_pages: true
  is_template: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: false

branches:
  - name: master

labels:
  - name: ex1
    color: fcba03
  - name: ex2
    color: fcba11
  - name: ex3
    color: fcba22
  - name: ex4
    color: fcba33
  - name: ex5
    color: fcba17
  - name: ex6
    color: fcba24
# extra labels
  - name: helm
    color: 42e9f5
    description: Helm helps you manage Kubernetes applications
  - name: github-tags
    color: 403c3c
    description: Github Tags Datasource
  - name: github-releases
    color: 403c3c
    description: Github Releases Datasource
  - name: gitlab-packages
    color: 403c3c
    description: Github Packages Datasource
