---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  releaseName: ingress-nginx
  chart:
    repository: https://kubernetes.github.io/ingress-nginx/
    name: ingress-nginx
    version: 1.0.0
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: datadog
  namespace: datadog
spec:
  releaseName: datadog
  chart:
    repository: https://helm.datadoghq.com/
    name: datadog
    version: 1.0.1
